
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Letra = 24;
  public static final int Boleano = 29;
  public static final int Parentesis_Cierre = 21;
  public static final int Entero_Real = 12;
  public static final int Coma = 22;
  public static final int Operador_Asignacion = 10;
  public static final int If = 37;
  public static final int LLave_Apertura = 18;
  public static final int Decremento = 27;
  public static final int Var = 14;
  public static final int Comentario = 33;
  public static final int Else = 38;
  public static final int Error = 31;
  public static final int Operador_Logico = 4;
  public static final int Vacio = 25;
  public static final int Return = 17;
  public static final int While = 16;
  public static final int NotacionCientifica = 32;
  public static final int Cadena = 13;
  public static final int EOF = 0;
  public static final int Operador_Potencia = 28;
  public static final int LLave_Cierre = 19;
  public static final int Function = 15;
  public static final int Simbolo = 26;
  public static final int error = 1;
  public static final int Parentesis_Apertura = 20;
  public static final int Terminador = 2;
  public static final int Operador_Multiplicacion = 7;
  public static final int Operador_Suma = 5;
  public static final int Comparador = 3;
  public static final int Operador_Division = 8;
  public static final int Decimal_Real = 23;
  public static final int Identificador = 11;
  public static final int Palabra_Reservada = 35;
  public static final int Operador_Resta = 6;
  public static final int ClaveReservada = 36;
  public static final int Corchete_Apertura = 30;
  public static final int Corchete_Cierre = 34;
  public static final int Operador_Residuo = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Terminador",
  "Comparador",
  "Operador_Logico",
  "Operador_Suma",
  "Operador_Resta",
  "Operador_Multiplicacion",
  "Operador_Division",
  "Operador_Residuo",
  "Operador_Asignacion",
  "Identificador",
  "Entero_Real",
  "Cadena",
  "Var",
  "Function",
  "While",
  "Return",
  "LLave_Apertura",
  "LLave_Cierre",
  "Parentesis_Apertura",
  "Parentesis_Cierre",
  "Coma",
  "Decimal_Real",
  "Letra",
  "Vacio",
  "Simbolo",
  "Decremento",
  "Operador_Potencia",
  "Boleano",
  "Corchete_Apertura",
  "Error",
  "NotacionCientifica",
  "Comentario",
  "Corchete_Cierre",
  "Palabra_Reservada",
  "ClaveReservada",
  "If",
  "Else"
  };
}

