package code;

public enum Tokens {
    Var,
    Return,
    If,
    Else,
    While,
    Function,
    Palabra_Reservada,
    Letra,
    Operador_Suma,
    Operador_Resta,
    Operador_Multiplicacion,
    Operador_Division,
    Identificador,
    Numero,
    Corchete_Apertura,
    Corchete_Cierre,
    LLave_Apertura,
    LLave_Cierre,
    Entero_Real,
    Decimal_Real,
    Operador_Logico,
    Operador_Asignacion,
    Terminador,
    Parentesis_Apertura,
    Simbolo,
    Parentesis_Cierre,
    Comparador,
    Cadena,
    Coma,
    Comentario,
    Incremento,
    Decremento,
    Boleano,
    Operador_Residuo,
    Potencia,
    Vacio,
    ClaveReservada,
    NotacionCientifica,
    Error

}
